CREATE TABLE IF NOT EXISTS `ethnicities` (
  `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(32) NOT NULL,
  `family`  VARCHAR(32) NOT NULL,
  `branch`  VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Bororo', 'Boróro', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Umutina', 'Boróro', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guató', 'Guató', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Apinayé', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanela', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanela Apaniekra', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanela Rankocamekra', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Gavião Krikatejê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Gavião Parkatejê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Gavião Pukobiê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Krahô', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Krahô-Kanela', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Krenyê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Krikati', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kokuiregatejê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Timbira', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaingang', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kayapó', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Panará', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kisêdjê', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapayuna', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xacriabá', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xavante', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xerente', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xokléng', 'Jê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karajá', 'Karajá', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Javaé', 'Karajá', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xambioá', 'Karajá', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Krenák', 'Krenák', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Maxakali', 'Maxakali', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pataxó', 'Maxakali', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pataxo Há-Há-Há', 'Maxakali', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ofayé', 'Ofayé', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Rikbaktsa', 'Rikbaktsa', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Fulni-ô', 'Yatê', 'Macro-Jê');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karitiana', 'Arikém', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aweti', 'Awetí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yudjá', 'Jurúna', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xipáya', 'Jurúna', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sateré-Mawé', 'Mawé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arara do Aripuanã', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aruá', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Cinta Larga', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Gavião de Rondônia', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Zoró', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Salamãy', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Suruí de Rondônia', 'Mondé', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mundurukú', 'Mundurukú', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kuruáya', 'Mundurukú', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Puroborá', 'Puroborá', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arara de Rondônia', 'Ramaráma', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Urucú', 'Ramaráma', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ajuru', 'Tuparí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Akuntsú', 'Tuparí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Makuráp', 'Tuparí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sakurabiat', 'Tuparí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tuparí', 'Tuparí', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Amanayé', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Anambé', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Apiaká', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Araweté', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Asurini do Tocantins', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Parakanã', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Suruí do Pará', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Asurini do Xingu', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ava-Canoeiro', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guajá', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guaraní', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guarani Kaiowá', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guarani Mbya', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guarani Nhandeva', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ka´apor', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kamayurá', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Amondáwa', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Diahói', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Juma', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karipuna', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kawahíb', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Parintintim', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tenharim', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Uru-Eu-Wau-Wau', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaiabi', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kokama', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kambéba', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapirapé', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tenetehara', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tembé', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tamoio (1)', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Turiwára', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Waiãpy', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xetá', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Zo´é', 'Tupi-Guarani', 'Tupi');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Apurinã', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ashaninka', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Baniwa', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kuripako', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Baré', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Enawenê-Nawê', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaixana', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kinikinau', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Manchineri', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mawayána', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mehináku', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Palikur', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Paresí', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tariana', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Terena', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wapixana', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Warekena', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wauja', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yawalapití', 'Aruak', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Apalaí', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arara do Pará', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Bakairí', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Galibi do Oiapoque', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Hixkaryána', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ikpeng', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ingarikó', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kalapalo', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kuikuro', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Matipú', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Nahukuá', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Naravute', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaxuyana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Makuxí', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kapon Patamóna', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Taulipáng', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tiriyó', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wai Wai', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karafawyana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Katuena', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tunayana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xereu', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yaipiyana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Waimiri Atroari', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wayana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ye´kuana', 'Karib', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arara do Acre', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Katukina do Acre', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaxarari', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaxinawá', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Korúbo', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kulina Páno', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Marúbo', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Matís', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Matsés', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Maya', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Nukiní', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Poyanáwa', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Shanenáwa', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yamináwa', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yawanawá', 'Pano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arapáso', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Bará', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Barasána', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Desána', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karapanã', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wanana', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kubeo', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Makúna', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Siriano', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tukano', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tuyúca', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yurutí', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Piratapuya', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mirititapuia', 'Tukano', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Banawa', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Dení', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Jamamadí', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Jarawára', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanamanti', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kulina Madijá', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Paumarí', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Zuruahã', 'Arawá', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanamarí', 'Katukina', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Katukina', 'Katukina', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Katawixí', 'Katukina', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Makú', 'Makú (Nadahup)', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Dâw', 'Makú (Nadahup)', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Hupda', 'Makú (Nadahup)', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Nadëb', 'Makú (Nadahup)', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Manduka', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Halotesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kithaulu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wakalitesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sawentesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Alaketesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Alantesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Hahaintesu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sarare', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Waikisu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wasusu', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Lakondê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Latundê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Negarotê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mamaindê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tawandê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sabanê', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Nambikwára', 'Nambikwára', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kujubim', 'Txapakúra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Migueléno', 'Txapakúra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Oro Win', 'Txapakúra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Torá', 'Txapakúra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pakaa Nova', 'Txapakúra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Ninám', 'Yanomamí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sanumá', 'Yanomamí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yanomán', 'Yanomamí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Yanomámi', 'Yanomamí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Bóra', 'Bóra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Miránha', 'Bóra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kadiwéu', 'Guaikurú', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Guaikurú', 'Guaikurú', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Múra', 'Múra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pirahã', 'Múra', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Chamakóko', 'Samúko', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Chiquitáno', 'Chiquito', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arikapú', 'Jabutí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Djeoromitxí - Jabutí', 'Jabutí', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Witóto', 'Witóto', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aconã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aikaná', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aimore (1)', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Anacé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Apolima - Arara', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Aranã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arapiun', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arikén', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Arikosé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Atikum', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Baenã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Borari', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Botocudo', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Catokin', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Charrua', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Galibí Marwórno', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Irántxe', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Issé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Jaricuna', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Jeripancó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaeté', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kahyana', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaimbé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kalabaça', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kalankó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kamakã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kamba', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kambiwá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kambiwá-Pipipã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kampé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanindé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kanoé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kantaruré', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kapinawá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karapotó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karijó (1)', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Karipúna do Amapá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kariri', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kariri - Xocó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kaxixó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kayuisiana', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kiriri', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Koiupanká', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kontanawá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Kwazá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Laiana', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Manao', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Maragua', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Marimã', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Maytapu', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mucurim', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Mynky', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Nawa', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Paiaku', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pankará', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pankararé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pankararú', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pankararú - Karuazu', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pankaru', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Papavó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Paumelenho', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Piri-Piri', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Pitaguari', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Potiguara', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Puri', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Sapará', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tabajara', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapajós (1)', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapeba', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapiuns', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tapuia', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tikúna', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tingui-Botó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tremembé', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Truká', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Trumái', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tumbalalá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tupaiu', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tupinambá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tupinambaraná', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tupiniquim', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Tuxá', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Wassú', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xocó', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xucuru', 'Não classificada em família', 'Não classificada em tronco');
INSERT INTO `ethnicities` (`name`, `family`, `branch`) VALUES ('Xucuru - Kariri', 'Não classificada em família', 'Não classificada em tronco');
